### PLAYLIST ###
index_playlist:
  path: /api/playlists
  controller: App\Controller\PlaylistController::index
  methods: GET

create_playlist:
  path: /api/playlists
  controller: App\Controller\PlaylistController::createPlaylist
  methods: POST

show_playlist:
  path: /api/playlists/{id}
  controller: App\Controller\PlaylistController::showPlaylist
  methods: GET

modify_playlist:
  path: /api/playlists/{id}
  controller: App\Controller\PlaylistController::modifyPlaylist
  methods: PUT

delete_playlist:
  path: /api/playlists/{id}
  controller: App\Controller\PlaylistController::deletePlaylist
  methods: DELETE

add_track:
  path: /api/playlists/addtrack
  controller: App\Controller\PlaylistController::addTrack
  methods: POST

file_upload:
  path: api/file/upload
  controller: App\Controller\FileController::upload
  methods: POST

api_account:
  path: /api/accounts/logged-in-user
  controller: App\Controller\AccountController::accountApi
  methods: GET

list_account:
  path: /api/accounts
  controller: App\Controller\AccountController::list
  methods: GET

update_account:
  path: /api/accounts/{id}
  controller: App\Controller\AccountController::update
  methods: PUT

change_account_password:
  path: /api/accounts/change_pass/{id}
  controller: App\Controller\AccountController::changePassword
  methods: POST

delete_account:
  path: /api/accounts/{id}
  controller: App\Controller\AccountController::delete
  methods: DELETE

### AUTHENTICATION ENDPOINTS ###

email_login:
  path: /api/login/email
  controller: App\Controller\LoginController::emailLogin
  methods: POST

phone_login:
  path: /api/login/phone
  controller: App\Controller\LoginController::phoneLogin
  methods: POST
  
logout:
  path: /api/logout
  controller: App\Controller\LoginController::logout
  methods: GET

email_registration:
  path: /api/registration/email
  controller: App\Controller\RegistrationController::emailRegistration
  methods: POST

phone_registration:
  path: /api/registration/phone
  controller: App\Controller\RegistrationController::phoneRegistration
  methods: POST

send_email_verification:
  path: /api/verify/email/send
  controller: App\Controller\VerificationController::emailVerification
  methods: POST

verify_email:
  path: /verify/email/{url}
  controller: App\Controller\VerificationController::verifyEmail
  methods: GET

send_email_reset:
  path: /api/reset/email/send
  controller: App\Controller\ResetController::emailRequestCreation
  methods: POST

activate_reset_email:
  path: /reset/email/{url}
  controller: App\Controller\ResetController::activateResetEmail
  methods: GET

reset_password_email:
  path: /api/reset/email/update
  controller: App\Controller\ResetController::resetPasswordEmail
  methods: POST

### END AUTHENTICATION ENDPOINTS ###

### MYTRACKLIST ENDPOINTS ###

index_mytracklist:
  path: /api/mytracklist
  controller: App\Controller\MyTracklist\MyTracklistController::index
  methods: GET

create_mytracklist:
  path: /api/mytracklist/create
  controller: App\Controller\MyTracklist\MyTracklistController::create
  methods: GET

store_mytracklist:
  path: /api/mytracklist
  controller: App\Controller\MyTracklist\MyTracklistController::store
  methods: POST

show_mytracklist:
  path: /api/mytracklist/{id}
  controller: App\Controller\MyTracklist\MyTracklistController::show
  methods: GET

edit_mytracklist:
  path: /api/mytracklist/{id}/edit
  controller: App\Controller\MyTracklist\MyTracklistController::edit
  methods: GET

update_mytracklist:
  path: api/mytracklist/{id}
  controller: App\Controller\MyTracklist\MyTracklistController::update
  methods: POST

delete_mytracklist:
  path: /api/mytracklist/{id}
  controller: App\Controller\MyTracklist\MyTracklistController::delete
  methods: DELETE

### END MYTRACKLIST ENDPOINTS ###

### PROFILE ENDPOINTS ###
upload_profile_photo:
  path: /api/profile/about/photo
  controller: App\Controller\ProfileController::uploadProfilePhoto
  methods: POST
get_profile_photo:
  path: /api/profile/about/photo
  controller: App\Controller\ProfileController::getProfilePhoto
  methods: GET
delete_profile_photo:
  path: /api/profile/about/photo
  controller: App\Controller\ProfileController::deleteProfilePhoto
  methods: DELETE
show_user_info:
  path: /api/profile/about/info
  controller: App\Controller\ProfileController::showUserInfo
  methods: GET
update_user_info:
  path: /api/profile/about/info/{id}
  controller: App\Controller\ProfileController::updateUserInfo
  methods: PUT
### END PROFILE ENDPOINTS ###

### BURGER ENDPOINTS ###
add_to_nextup:
  path: api/burger/addnextup/{id}
  controller: App\Controller\BurgerController::addNextUp
  methods: GET

share_song:
  path: api/burger/sharesong/{id}
  controller: App\Controller\BurgerController::shareSong
  methods: GET

go_to_artist:
  path: api/burger/gotoartist
  controller: App\Controller\BurgerController::getArtist
  methods: POST

go_to_album:
  path: api/burger/gotoalbum
  controller: App\Controller\BurgerController::getAlbum
  methods: POST
### END BURGER ENDPOINTS ###

### TEST ENDPOINTS ###
ping:
  path: /api/ping
  controller: App\Controller\PingController::ping
  methods: GET
### END TEST ENDPOINTS ###